context:
  version: "26.4.1"

package:
  name: twiggy-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/twiggy-language-server/-/twiggy-language-server-${{ version }}.tgz
  sha256: 1a557d36104b45e0fa792eb0eb558367a7efecbbee8e4704a42880116eb3b9f0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - twiggy-language-server --node-ipc

about:
  license: MPL-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: TypeScript-powered language server for Twig templates.
  homepage: https://github.com/moetelo/twiggy
  repository: https://github.com/moetelo/twiggy

extra:
  recipe-maintainers:
    - danielnachun
